name: t_polls_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  appinio_swiper: ^2.1.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  logging: ^1.2.0
  running_text: ^0.1.2
  telegram_web_app: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
